name: Ruff Lint
on: [push, pull_request]
jobs:
  ruff:
    name: Run Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3

      - name: Check formatting
        run: ruff format --check --diff

      - name: Lint
        run: ruff check
